# Generated by Django 3.2.9 on 2021-11-23 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productivity', '0005_celebrities_hotels_resell_tourisms'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='celebrities',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ownbusiness',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='resell',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tourisms',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='celebrities',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownbusiness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resell',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shops',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourisms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
