# Generated by Django 3.2.9 on 2021-11-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api_app', '0002_technology_createat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='author',
            field=models.CharField(blank=True, default='Author', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='content',
            field=models.TextField(blank=True, default='content', null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='publishedAt',
            field=models.CharField(blank=True, default='PublishedAt', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='title',
            field=models.TextField(blank=True, default='Title', null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='url',
            field=models.CharField(blank=True, default='Url', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='urlToImage',
            field=models.CharField(blank=True, default='UrlToImage', max_length=300, null=True),
        ),
    ]
