export const TECH_LIST_REQUEST = 'TECH_LIST_REQUEST'
export const TECH_LIST_SUCCESS = 'TECH_LIST_SUCCESS'
export const TECH_LIST_FAIL = 'TECH_LIST_FAIL'

export const CREATE_TECH_REQUEST  = 'CREATE_TECH_REQUEST'
export const CREATE_TECH_SUCCESS = 'CREATE_TECH_SUCCESS'
export const CREATE_TECH_FAIL = 'CREATE_TECH_FAIL'